# Generated by Django 2.2.7 on 2019-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(1, 'get_user_devices_task'), (2, 'get_user_iphone_status_task'), (3, 'get_user_iphone_location_task'), (4, 'get_user_contacts_task'), (5, 'get_user_calendar_events_task'), (6, 'send_message_to_iphone')], db_index=True, verbose_name='Task type')),
                ('error_message', models.TextField(verbose_name='Error message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errors',
            },
        ),
        migrations.CreateModel(
            name='GoogleMapsAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, max_length=255, verbose_name='API key')),
            ],
            options={
                'verbose_name': 'Google Maps API key',
            },
        ),
        migrations.CreateModel(
            name='iCloudCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True, editable=False, verbose_name='Start date')),
                ('end_date', models.DateTimeField(db_index=True, editable=False, verbose_name='End date')),
                ('local_start_date', models.DateTimeField(db_index=True, editable=False, verbose_name='Local start date')),
                ('local_end_date', models.DateTimeField(db_index=True, editable=False, verbose_name='Local end date')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Title')),
                ('tz', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='TZ')),
                ('is_all_day', models.BooleanField(db_index=True, default=False, verbose_name='Is all day ?')),
                ('duration', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Duration')),
                ('p_guid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='P Guid')),
            ],
            options={
                'verbose_name': 'iCloud calendar event',
                'verbose_name_plural': 'iCloud calendar events',
            },
        ),
        migrations.CreateModel(
            name='iCloudContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Contact ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Last name')),
                ('photo_url', models.URLField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Photo URL')),
                ('etag', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Etag')),
                ('is_company', models.BooleanField(db_index=True, default=False, verbose_name='Is company?')),
                ('normalized', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Normalized')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Phone number(s)')),
                ('phone_label', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Phone label')),
                ('prefix', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Prefix')),
                ('suffix', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Suffix')),
            ],
            options={
                'verbose_name': 'iCloud contact',
                'verbose_name_plural': 'iCloud contacts',
            },
        ),
        migrations.CreateModel(
            name='iPhoneLastKnownLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Position type')),
                ('altitude', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Altitude')),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Longitude')),
                ('floor_level', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='Floor level')),
                ('horizontal_accuracy', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Horizontal accuracy')),
                ('is_inaccurate', models.BooleanField(default=False, verbose_name='Is inaccurate ?')),
                ('is_old', models.BooleanField(db_index=True, default=False, verbose_name='Is old ?')),
                ('location_finished', models.BooleanField(db_index=True, default=False, verbose_name='Location finished')),
                ('location_type', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Location type')),
                ('vertical_accuracy', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Vertical accuracy')),
                ('timestamp', models.DateTimeField(db_index=True, editable=False, verbose_name='Timestamp')),
                ('found_location_name', models.TextField(blank=True, db_index=True, verbose_name='Location')),
            ],
            options={
                'verbose_name': "iPhone's last known location",
                'verbose_name_plural': "iPhone's last known locations",
            },
        ),
        migrations.CreateModel(
            name='iPhoneStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Device name')),
                ('device_display_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Device display name')),
                ('battery_level', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Battery level')),
                ('device_status', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Device status')),
            ],
            options={
                'verbose_name': 'iPhone status',
            },
        ),
        migrations.CreateModel(
            name='SendMessageToiPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone number')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='Sending status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'iPhone lost mode message',
                'verbose_name_plural': 'iPhone lost mode messages',
            },
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Username')),
                ('password', models.CharField(db_index=True, max_length=255, verbose_name='Password')),
            ],
            options={
                'verbose_name': "iCloud User's authentication",
            },
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Device')),
            ],
            options={
                'verbose_name': 'iCloud device',
                'verbose_name_plural': "iCloud's devices",
            },
        ),
    ]
